default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  encoding: utf8
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_USER_PASSWORD'] %>
  host: <%= ENV['DB_RDS_HOST'] %>
  port: <%= ENV['DB_RDS_PORT'] %>

production:
  <<: *default
  database: ucsc_ext_course_production

development:
  <<: *default
  database: ucsc_ext_course_development

test:
  <<: *default
  database: ucsc_ext_course_test
